### ISSUE TITLE
All calls error out except get_patch_notes() and get_user_achievements()

### ISSUE THREAD

**Issue by thetylerhayes** [anthok/overwatch-api#6]
Same response for `get_stats_all_heroes() ` and `get_stats() ` etc.:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/Sites/overwatch-api/env/lib/python2.7/site-packages/overwatch_api/overwatch_api.py", line 83, in get_stats_all_heroes
    'allHeroes/'
  File "/Users/username/Sites/overwatch-api/env/lib/python2.7/site-packages/overwatch_api/overwatch_api.py", line 129, in _base_request
    self.validate_response(r)
  File "/Users/username/Sites/overwatch-api/env/lib/python2.7/site-packages/overwatch_api/overwatch_api.py", line 94, in validate_response
    raise Exception
Exception
```

**Comment by thetylerhayes** [comment]
This includes even the exact sample calls in README like `ow.get_stats_all_heroes(PC,AMERICAS,'elyK-1940',QUICK)
`

**Comment by anthok** [comment]
Thanks for the heads up. I'm at a conference until Sunday, but I'll look into it first thing when I get back.

**Comment by anthok** [comment]
I updated the example code on the readme, don't go off test.py for now
