### ISSUE TITLE
Tests update needed

### ISSUE THREAD

**Issue by EmadMokhtar** [anthok/overwatch-api#8]
There are some APIs tested and they are changed.

test results
```
test_get_patch_notes (overwatch_api.tests.TestPatchNotes) ... ok
test_get_patch_notes_keys (overwatch_api.tests.TestPatchNotes) ... ok
test_get_profile (overwatch_api.tests.TestUserMethods) ... ok
test_get_profile_keys (overwatch_api.tests.TestUserMethods) ... ok
test_get_stats (overwatch_api.tests.TestUserMethods) ... ERROR
test_get_stats_all_heroes (overwatch_api.tests.TestUserMethods) ... ok
test_get_stats_all_heroes_keys (overwatch_api.tests.TestUserMethods) ... FAIL
test_get_stats_amount (overwatch_api.tests.TestUserMethods) ... ERROR
test_get_stats_one_hero (overwatch_api.tests.TestUserMethods) ... ERROR
test_get_stats_one_hero_keys (overwatch_api.tests.TestUserMethods) ... ERROR
test_get_user_achievements (overwatch_api.tests.TestUserMethods) ... ERROR
test_get_user_achievements_keys (overwatch_api.tests.TestUserMethods) ... ERROR

======================================================================
ERROR: test_get_stats (overwatch_api.tests.TestUserMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Emad/Projects/overwatch-api/overwatch_api/tests.py", line 111, in test_get_stats
    result = self.ow.get_stats(PC, AMERICAS, 'elyK-1940', QUICK)
AttributeError: 'OverwatchAPI' object has no attribute 'get_stats'

======================================================================
ERROR: test_get_stats_amount (overwatch_api.tests.TestUserMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Emad/Projects/overwatch-api/overwatch_api/tests.py", line 115, in test_get_stats_amount
    result = self.ow.get_stats(PC, AMERICAS, 'elyK-1940', QUICK)
AttributeError: 'OverwatchAPI' object has no attribute 'get_stats'

======================================================================
ERROR: test_get_stats_one_hero (overwatch_api.tests.TestUserMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Emad/Projects/overwatch-api/overwatch_api/tests.py", line 100, in test_get_stats_one_hero
    result = self.ow.get_stats_one_hero(PC, AMERICAS, 'elyK-1940', QUICK,
AttributeError: 'OverwatchAPI' object has no attribute 'get_stats_one_hero'

======================================================================
ERROR: test_get_stats_one_hero_keys (overwatch_api.tests.TestUserMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Emad/Projects/overwatch-api/overwatch_api/tests.py", line 105, in test_get_stats_one_hero_keys
    result = self.ow.get_stats_one_hero(PC, AMERICAS, 'elyK-1940', QUICK,
AttributeError: 'OverwatchAPI' object has no attribute 'get_stats_one_hero'

======================================================================
ERROR: test_get_user_achievements (overwatch_api.tests.TestUserMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Emad/Projects/overwatch-api/overwatch_api/tests.py", line 33, in test_get_user_achievements
    result = self.ow.get_user_achievements(PC, AMERICAS, 'elyK-1940')
AttributeError: 'OverwatchAPI' object has no attribute 'get_user_achievements'

======================================================================
ERROR: test_get_user_achievements_keys (overwatch_api.tests.TestUserMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Emad/Projects/overwatch-api/overwatch_api/tests.py", line 37, in test_get_user_achievements_keys
    result = self.ow.get_user_achievements(PC, AMERICAS, 'elyK-1940')
AttributeError: 'OverwatchAPI' object has no attribute 'get_user_achievements'

======================================================================
FAIL: test_get_stats_all_heroes_keys (overwatch_api.tests.TestUserMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Emad/Projects/overwatch-api/overwatch_api/tests.py", line 97, in test_get_stats_all_heroes_keys
    self.assertEqual(set(result.keys()), expected_keys)
AssertionError: Items in the first set but not the second:
'ReconAssists-Average'

----------------------------------------------------------------------
Ran 12 tests in 34.691s

FAILED (failures=1, errors=6)
```

**Comment by anthok** [comment]
Good catch, I changed some of calls in the latest version to better reflect the lootbox API.
